version: '3'

services:
  todo-api:
    image: todoapi:latest
    container_name: todo-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - todo-service-net
  todo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
    networks:
      - todo-service-net
networks:
  todo-service-net:
    external: false